### ISSUE TITLE
typos in matteobrusa/Tumbless: A bloggin platfrom based only on Amazon S3 (and your browser)

### ISSUE THREAD

**Issue by anaran** [matteobrusa/Tumbless#3]
See:

https://github.com/matteobrusa/Tumbless

Details:

Perhaps it's a joke I don't get, but the repository description would look much better to me without these typos:

bloggin platfrom

http://mzl.la/1vxCDgA

**Comment by matteobrusa** [comment]
Thanks for the tip, I've fixed it.

Cheers,
Matteo
